// sprites.js — every creature, drawn from scratch as text pixel-maps.
// One shared palette; '.' = transparent. Frame index layouts follow the
// engine's expectations (documented at each sheet).
'use strict';

const SPRITES = (() => {
  const PAL = PX.palette({
    k: '#1a1129', K: '#0d0817',
    w: '#f4f6ff', W: '#c9d2ec',
    f: '#f2b58c', F: '#d68d62',
    B: '#2e49b8', b: '#1f2f7e', L: '#4d6ce0',
    G: '#ffd75e', g: '#c79a2a',
    o: '#7df0ff', O: '#2ab8d8',
    s: '#8a5a32', S: '#5e3a1e',
    d: '#4a3560',
    r: '#e04f2a', R: '#9c2e1a',
    n: '#5fae4a', N: '#3c7a30',
    m: '#9aa6c0', M: '#5d6884', h: '#ccd6ea',
    p: '#7a4a8e', P: '#50305e',
    y: '#e8e6d4', Y: '#b3b09a',
    c: '#aef4ff',
    t: '#ff9a3c', T: '#e04f2a', e: '#ffd75e',
    v: '#8d6cc8', V: '#5d4488',
    q: '#4a9e58', Q: '#2e6e3c', x: '#c8e09a',
    z: '#6e5a86', Z: '#4a3a60',
    u: '#f4f6ffd8', U: '#b8c4e8c0',
    i: '#aef4ff66', I: '#7df0ff99',
    a: '#fff1a8',
  });

  const f = (art) => PX.frame(art, PAL);
  const mir = PX.mirror;

  // upscale a frame by n (chunky big sprites like bosses)
  function scale(fr, n) {
    const cv = document.createElement('canvas');
    cv.width = fr.w * n; cv.height = fr.h * n;
    const ctx = cv.getContext('2d');
    ctx.imageSmoothingEnabled = false;
    ctx.drawImage(fr.canvas, 0, 0, cv.width, cv.height);
    const mask = new Uint8Array(cv.width * cv.height);
    for (let y = 0; y < cv.height; y++)
      for (let x = 0; x < cv.width; x++)
        mask[y * cv.width + x] = fr.mask[(y / n | 0) * fr.w + (x / n | 0)];
    return { canvas: cv, w: cv.width, h: cv.height, mask };
  }

  /* ============================== THE WIZARD ==============================
     16x24. Sheet has 32 slots with this layout:
     0-7 walk right, 8 idle, 9 jump/fall, 10 duck, 11 brake, 12 dazed(dead),
     13 invisible-shimmer, 14/15 blank, 16-31 = left-facing mirrors.       */

  const WIZ_TOP = `
......kk........
.....kBBk....koc
.....kBLBk...kco
....kBBLBk...koc
....kBBBBBk...s.
...kBBBBBBk...s.
...kGgGgGGk...s.
..kBBBBBBBBk..s.
.k.kffffffk.k.s.
....kfkffkf...s.
....kffffff...s.
...kwwffffww..s.
...kwWwwwwWw..s.
..kBwWWwwWWwk.s.
..kBBwWWWWwBkks.
..kBBkwwwwkBBks.
..kLBGgGgGBBLks.
..kBBBBBBBBBk.s.
..kBBBBBBBBk..s.
..kbBBBBBBbk..s.
..kbbBBBBbbk..s.`;

  const LEGS = [
    `..kdkkkkkkdk..s.
...kddk.kddk..s.
...kkkk.kkkk..s.`,
    `...kdkkkkdk...s.
....kddddk....s.
....kkkkkk....s.`,
    `..kdkkkkkkdk..s.
..kddk...kddk.s.
..kkkk...kkkk.s.`,
    `...kdkkkkdk...s.
....kddddk....s.
....kkkkkk....s.`,
  ];

  function wizWalk(i) { return f(WIZ_TOP + '\n' + LEGS[i]); }

  const WIZ_JUMP = f(WIZ_TOP + `
...kdkkkkkkd..s.
..kddk..kddk..s.
..kkk....kkk..s.`);

  const WIZ_DUCK = f(`
................
................
................
................
................
................
................
......kk........
.....kBBk....koc
.....kBLBk...kco
....kBBLBk...koc
....kBBBBBk..ks.
...kBBBBBBk...s.
...kGgGgGGk...s.
..kBBBBBBBBk..s.
..kkffffffkk..s.
...kfkffkfk...s.
...kffffffk...s.
..kwwffffwwk..s.
..kBwWwwwWwBk.s.
..kBBwwwwwBBk.s.
..kbBBBBBBBbk.s.
..kdkkkkkkkdk.s.
..kkkk...kkkk.s.`);

  const WIZ_DEAD = f(`
................
................
................
................
................
.....a.....a....
...a..........a.
......kkkk......
....kkBBBBkk....
...kBBBLBBBBk...
..kBBBBBBBBBBk..
..kGgGgGgGgGGk..
.kBBBBBBBBBBBBk.
..kffffffffffk..
...fkxfkkfxkf...
...kffffffffk...
..kwwfkkkkfwwk..
..kwWwwwwwwWwk..
..kBwWWwwwWwBk..
..kBBwwwwwwBBk..
..kbBBBBBBBBbk..
.kdkkkkkkkkkkdk.
.kddk......kddk.
.kkkk......kkkk.`);

  const WIZ_INVIS = f(`
......ii........
.....i..i....i.i
................
....i...i......i
..............i.
...i.....i......
..............i.
..i........i....
..............i.
....i...........
..............i.
...i......i.....
..............i.
..i.........i...
..............i.
..i.........i.i.
..............i.
..i.........i...
..............i.
..i........i..i.
...i......i.....
..i.i.....i.....
...i..i..i.i..i.
...i.ii..ii...i.`);

  const wizR = [wizWalk(0), wizWalk(1), wizWalk(2), wizWalk(3)];
  const wizIdle = wizWalk(1);
  const blank16x24 = PX.blank(16, 24);
  const wizFrames = [
    wizR[0], wizR[1], wizR[2], wizR[3], wizR[0], wizR[1], wizR[2], wizR[3],
    wizIdle, WIZ_JUMP, WIZ_DUCK, wizIdle, WIZ_DEAD, WIZ_INVIS, blank16x24, blank16x24,
  ];
  const wiz = PX.sheet(wizFrames.concat(wizFrames.map(fr => fr === blank16x24 ? fr : mir(fr))));

  /* ============================ GUARD (goblin) ============================
     16x21, frames [right0, right1, left0, left1] (matches a = step|(xx&2)
     where xx=-1 -> left frames 2,3). Spear forward, scrappy walker.       */
  const GUARD_A = f(`
.......kkk....r.
......kmmmk..krk
.....kmmhmmk.kgk
.....kmmmmmk..s.
.....knnnnk...s.
....knkn.nk...s.
....knnnnnk...s.
.....knnnk....s.
...kNnnnnnNk..s.
..knkNNNNNknk.s.
..knkNnnnNknks.
..knkNnnnNkknks.
...kkNNNNNk.kk..
....kNnnnNk.....
....kNnnnNk.....
.....kNNNk......
....kNnknNk.....
....kNnknnNk....
...kSskkkSsk....
...kssk.kssk....
...kkkk.kkkk....`);
  const GUARD_B = f(`
.......kkk....r.
......kmmmk..krk
.....kmmhmmk.kgk
.....kmmmmmk..s.
.....knnnnk...s.
....knkn.nk...s.
....knnnnnk...s.
.....knnnk....s.
...kNnnnnnNk..s.
..knkNNNNNknk.s.
..knkNnnnNknks.
..knkNnnnNkknks.
...kkNNNNNk.kk..
....kNnnnNk.....
....kNnnnNk.....
.....kNNNk......
.....kNnnNk.....
.....kNnnNk.....
....kSskssk.....
....kssksskk....
....kkkkkkkk....`);
  const guard = PX.sheet([GUARD_A, GUARD_B, mir(GUARD_A), mir(GUARD_B)]);

  /* ======================= SENTRY (hooded watcher) ========================
     16x24, frames [right0, right1, left0, left1]. Hovers, lantern eyes.   */
  const SENTRY_A = f(`
......kkkk......
.....kppppk.....
....kpPppppk....
...kpPkkkkppk...
...kpkGkkGkpk...
...kpkkkkkkpk...
...kpPkkkkPpk...
...kppPkkPppk...
..kpppppppppk...
..kpppvpppppk...
..kpvpppppvppk..
..kppppvppppk...
.kpppvppppvppk..
.kppppppvpppppk.
.kPpvppppppvpPk.
..kPpppvppppPk..
..kPPpppppPPk...
...kPPpvpPPk....
....kPPpPPPk....
.....kPpPk......
......kPPPk.....
.......kPk......
......kPk.......
.......k........`);
  const SENTRY_B = f(`
......kkkk......
.....kppppk.....
....kpPppppk....
...kpPkkkkppk...
...kpkGkkGkpk...
...kpkkkkkkpk...
...kpPkkkkPpk...
...kppPkkPppk...
..kpppppppppk...
..kpppvpppppk...
..kpvpppppvppk..
..kppppvppppk...
.kpppvppppvppk..
.kppppppvpppppk.
.kPpvppppppvpPk.
..kPpppvppppPk..
..kPPpppppPPk...
...kPPpvpPPk....
....kPPPpPk.....
......kPpPk.....
.....kPPPk......
......kPk.......
.......kPk......
........k.......`);
  const sentry = PX.sheet([SENTRY_A, SENTRY_B, mir(SENTRY_A), mir(SENTRY_B)]);

  /* ====================== KNIGHT (halberd sentinel) =======================
     16x44, 2 frames (halberd low / high). A tall living statue to leap.   */
  const KNIGHT_A = f(`
.............kk.
............kGgk
............kgk.
.....rr......ks.
....rrr......ks.
...rrrk......ks.
..krrk.......ks.
..kkmmmk....khsk
..kmmhmmk...khhk
..kmhhhmk...khsk
..kmmmmmk....ks.
..kmkkkmk....ks.
..kmkkkmk....ks.
..kmmmmmk....ks.
...kmmmk.....ks.
..kmmhmmk....ks.
.kmmmmmmmk...ks.
.kmhmmmhmmk..ks.
kmmmmmmmmmk..ks.
kmkmmhmmkmk..ks.
kmkmmmmmkmkkkks.
kmkmhhhmkmkmkks.
kmkmmmmmkmmmkks.
kmkmhhhmkmkkkks.
.kkmmmmmkk...ks.
..kmhhhmk....ks.
..kmmmmmk....ks.
..kmhhhmk....ks.
..kmmmmmk....ks.
..kMmmmMk....ks.
..kMmmmMk....ks.
..kMMMMMk....ks.
...kMMMk.....ks.
..kMMmMMk....ks.
..kMmmmMk....ks.
..kMmmmMk....ks.
..kMMMMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
.kMMMkMMMk...ks.
.kkkkkkkkk...kk.`);
  const KNIGHT_B = f(`
.............kk.
............kGgk
............kgk.
.....rr......ks.
....rrr......ks.
...rrrk......ks.
..krrk......khsk
..kkmmmk....khhk
..kmmhmmk...khsk
..kmhhhmk....ks.
..kmmmmmk....ks.
..kmkkkmk....ks.
..kmkkkmk....ks.
..kmmmmmk....ks.
...kmmmk.....ks.
..kmmhmmk....ks.
.kmmmmmmmk...ks.
.kmhmmmhmmk..ks.
kmmmmmmmmmk..ks.
kmkmmhmmkmk..ks.
kmkmmmmmkmkkkks.
kmkmhhhmkmkmkks.
kmkmmmmmkmmmkks.
kmkmhhhmkmkkkks.
.kkmmmmmkk...ks.
..kmhhhmk....ks.
..kmmmmmk....ks.
..kmhhhmk....ks.
..kmmmmmk....ks.
..kMmmmMk....ks.
..kMmmmMk....ks.
..kMMMMMk....ks.
...kMMMk.....ks.
..kMMmMMk....ks.
..kMmmmMk....ks.
..kMmmmMk....ks.
..kMMMMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
..kMMkMMk....ks.
.kMMMkMMMk...ks.
.kkkkkkkkk...kk.`);
  const knight = PX.sheet([KNIGHT_A, KNIGHT_B]);

  /* ======================== ARCHER (bone bowman) ==========================
     16x28, frames: 0 idle-left, 1 fire-left, 2 idle-right, 3 fire-right.  */
  const ARCH_IDLE_R = f(`
.....kkkk.......
....kNNNNk......
...kNNNNNNk.....
...kNkkkkNk.....
...kNkykyNk.....
...kNyyyyNk..k..
....kyykyk...sk.
....kyyyyk...sk.
.....kyyk...ks..
...kNNNNNNk.ks..
..kNNNNNNNNks...
..kNkNNNNkNks...
..kNkNNNNkyks...
..kNkNNNNkks....
..kykNNNNkks....
.....NNNN..ks...
....kNNNNk..sk..
....kNNNNk..sk..
....kNNNNk...k..
....kyykyy......
....kyykyy......
....kyykyy......
.....kkkkk......
....kyykyyk.....
....kyykyyk.....
...kYykkYyk.....
...kyyk.kyyk....
...kkkk.kkkk....`);
  const ARCH_FIRE_R = f(`
.....kkkk.......
....kNNNNk......
...kNNNNNNk.....
...kNkkkkNk.....
...kNkykyNk.....
...kNyyyyNk..k..
....kyykyk..ks..
....kyyyyk..ks..
.....kyyk..ks...
...kNNNNNNkks...
..kNNNNNNNyks...
..kNkNNNNsssssk.
..kNkNNNNkyks...
..kNkNNNNkks....
..kykNNNNkks....
.....NNNN.ks....
....kNNNNk.sk...
....kNNNNk.sk...
....kNNNNk..k...
....kyykyy......
....kyykyy......
....kyykyy......
.....kkkkk......
....kyykyyk.....
....kyykyyk.....
...kYykkYyk.....
...kyyk.kyyk....
...kkkk.kkkk....`);
  const archer = PX.sheet([mir(ARCH_IDLE_R), mir(ARCH_FIRE_R), ARCH_IDLE_R, ARCH_FIRE_R]);

  /* ========================== ARROW ==========================
     16x7, frames 0-3 fly LEFT, 4-7 fly RIGHT (wobble pairs).   */
  const ARROW_L1 = f(`
................
.............ww
kk...........ww
wkkssssssssskww
kk...........ww
.............ww
................`);
  const ARROW_L2 = f(`
................
.............ww
.kk..........ww
wkkssssssssskww
.kk..........ww
.............ww
................`);
  const arrow = PX.sheet([ARROW_L1, ARROW_L2, ARROW_L1, ARROW_L2,
                          mir(ARROW_L1), mir(ARROW_L2), mir(ARROW_L1), mir(ARROW_L2)]);

  /* ========================== GHOST ==========================
     16x24, frames [left0,left1,right0,right1] (a = xx<0?0:2).  */
  const GHOST_L1 = f(`
.....kkkkk......
...kkuuuuukk....
..kuuuuuuuuk....
..kuuuuuuuuuk...
.kuukkuuukkuuk..
.kuukkuuukkuuk..
.kuuuuuuuuuuuk..
.kuuuuuuuuuuuk..
.kuuukkkkuuuuk..
.kuuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
..kUuuuuuuuuuk..
..kUuuuuuuuuk...
..kUuuuuuuuuuk..
.kUuuUuuUuuuuk..
.kUuUUuUUuUuuk..
..kUk.kUk.kUuk..
...k...k...kuk..
............k...
................`);
  const GHOST_L2 = f(`
.....kkkkk......
...kkuuuuukk....
..kuuuuuuuuk....
..kuuuuuuuuuk...
.kuukkuuukkuuk..
.kuukkuuukkuuk..
.kuuuuuuuuuuuk..
.kuuuuuuuuuuuk..
.kuuukkkkuuuuk..
.kuuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
.kUuuuuuuuuuuk..
..kUuuuuuuuuuk..
..kUuuuuuuuuuk..
..kUuuuuuuuuk...
.kUuuUuuUuuuk...
.kUUuUUuUUuuuk..
..kUk.kUk.kUUk..
....k...k..kk...
.............k..
................`);
  const ghost = PX.sheet([GHOST_L1, GHOST_L2, mir(GHOST_L1), mir(GHOST_L2)]);

  /* ========================== DRAGON =========================
     32x42, 4 frames -> [sit, flap, sit, flap]. Hopping wyvern. */
  const DRAGON_A = f(`
............kkkk................
...........kqqqqk...............
..........kqqqqqqk..............
..........kqkkqqqkk.............
..........kqkkqqqkGk............
..........kqqqqqqkk.............
...........kqqqqk..............
....().....kxxqqk...............
...........kxxqqk...............
.........kkxxqqqk...............
........kqxxxqqqk...............
.......kqqxxxqqqqk..............
......kqqxxxxqqqqk..............
.....kqqxxxxxqqqqqk.............
.....kqqxxxxxqqqqqk.............
....kqqxxxxxxqqqqqqk............
....kqqxxxxxxqqqqqqk............
....kqqxxxxxxqqqqqqk............
...kqqxxxxxxxqqqqqqqk...........
...kqqxxxxxxxqqqqqqqk...........
...kqqxxxxxxxqqqqqqqk...........
...kqqxxxxxxxqqqqqqqk...........
..kqqxxxxxxxxqqqqqqqqk..........
..kqqxxxxxxxxqqqqqqqqk..........
..kqqxxxxxxxxqqqqqqqqkk.........
..kqqxxxxxxxxqqqqqqqqkQk........
..kqQxxxxxxxqqqqqqqqqkQQk.......
..kqQQxxxxxqqqqqqqqqqkQQQk......
..kqqQQQQQQqqqqqqqqqkQQQQQk.....
...kqqqqqqqqqqqqqqqkQQQQQQQk....
...kqqqqqqqqqqqqqqkQQQQQQQk.....
....kqqqqqqqqqqqqkQQQQQQQk......
.....kqqqqqqqqqqkQQQQQQQk.......
......kqqqqqqqqkQQQQQQQk........
.......kqqqqqqkkkQQQQQk.........
......kqqkqqqk...kkkkk..........
.....kqqkkqqqk..................
....kqqk..kqqk..................
...kqqk....kqqk.................
..kQqqk....kQqqk................
..kQQQQk...kQQQQk...............
...kkkkk....kkkkk...............`);
  const DRAGON_B = f(`
............kkkk................
...........kqqqqk...............
..........kqqqqqqk..............
..........kqkkqqqkk.............
..........kqkkqqqkGk............
..........kqqqqqqkk.............
...........kqqqqk...............
...........kxxqqk....kkkk.......
...........kxxqqk..kkqqqqkk.....
.........kkxxqqqk.kqqqqqqqqk....
........kqxxxqqqkkqqqqkkqqqqk...
.......kqqxxxqqqqkqqkk..kkqqk...
......kqqxxxxqqqqkqk.......kk...
.....kqqxxxxxqqqqqk.............
.....kqqxxxxxqqqqqk.............
....kqqxxxxxxqqqqqqk............
....kqqxxxxxxqqqqqqk............
....kqqxxxxxxqqqqqqk............
...kqqxxxxxxxqqqqqqqk...........
...kqqxxxxxxxqqqqqqqk...........
...kqqxxxxxxxqqqqqqqk...........
...kqqxxxxxxxqqqqqqqk...........
..kqqxxxxxxxxqqqqqqqqk..........
..kqqxxxxxxxxqqqqqqqqk..........
..kqqxxxxxxxxqqqqqqqqkk.........
..kqqxxxxxxxxqqqqqqqqkQk........
..kqQxxxxxxxqqqqqqqqqkQQk.......
..kqQQxxxxxqqqqqqqqqqkQQQk......
..kqqQQQQQQqqqqqqqqqkQQQQQk.....
...kqqqqqqqqqqqqqqqkQQQQQQQk....
...kqqqqqqqqqqqqqqkQQQQQQQk.....
....kqqqqqqqqqqqqkQQQQQQQk......
.....kqqqqqqqqqqkQQQQQQQk.......
......kqqqqqqqqkQQQQQQQk........
.......kqqqqqqkkkQQQQQk.........
......kqqkqqqk...kkkkk..........
.....kqqkkqqqk..................
....kqqk..kqqk..................
...kqqk....kqqk.................
..kQqqk....kQqqk................
..kQQQQk...kQQQQk...............
...kkkkk....kkkkk...............`);
  const dragon = PX.sheet([DRAGON_A, DRAGON_B, DRAGON_A, DRAGON_B]);

  /* =========================== FISH ==========================
     16x24, frames 0-1 rising, 2-3 falling. Leaping koi.        */
  const FISH_UP1 = f(`
.......kk.......
......ktttk.....
.....kttttk.....
....kttkttttk...
....ktttttttk...
...kttttttttk...
...ktketttttk...
...kttttttttk...
..кttttttttk....
..kttttttttk....
..ktttttttk.....
.kt.ktttttk.....
.....kttttk.....
....kttttk......
....ktttk.......
...ktttk........
...kttk.........
..kttk..........
..kttkk.........
.kttkttk........
.ktkkttk........
.kk..kttk.......
......kk........
................`.replace(/к/g, 'k'));
  const FISH_UP2 = f(`
.......kk.......
......ktttk.....
.....kttttk.....
....kttkttttk...
....ktttttttk...
...kttttttttk...
...ktketttttk...
...kttttttttk...
..kttttttttk....
..kttttttttk....
..ktttttttk.....
.kt.ktttttk.....
.....kttttk.....
....kttttk......
....ktttk.......
...ktttk........
...kttk.........
..kttk..........
.kttk...........
.kttkkk.........
.ktkkttk........
.kk.kttk........
.....kk.........
................`);
  const FISH_DN1 = f(`
......kk........
.....kttkk......
....kttkttk.....
....ktkkttk.....
...kttkttk......
..kttkk.........
..kttk..........
...kttk.........
...ktttk........
....ktttk.......
....kttttk......
.....kttttk.....
.kt.ktttttk.....
..ktttttttk.....
..kttttttttk....
..kttttttttk....
...kttttttttk...
...ktketttttk...
...kttttttttk...
....ktttttttk...
....kttkttttk...
.....kttttk.....
......ktttk.....
.......kk.......`);
  const fish = PX.sheet([FISH_UP1, FISH_UP2, FISH_DN1, mir(FISH_DN1)]);

  /* ========================== BOULDER ========================
     16x16, 4 frames (2 variants repeated) - tumbling granite.  */
  const BOULDER_A = f(`
.....kkkkk......
...kkmmmmmkk....
..kmmhhmmmmmk...
.kmhhmmmmkmmk...
.kmhmmmmkmmmmk..
kmmmmmmkmmmmmk..
kmmmmmkmmmmmMk..
kmhmmmmmmmmMMk..
kmmmmmmkmmmmMk..
kmmmkkkmmmMmMk..
kmmkmmmmmMMMk...
.kmmmmmMmMMMk...
.kMmmMMMMMMk....
..kMMMMMMMk.....
...kkMMMkk......
.....kkkk.......`);
  const BOULDER_B = f(`
.....kkkkk......
...kkmmmmmkk....
..kmmmmkmmmk....
.kmmmmkmmmmmk...
.kmhmmkmmmmmmk..
kmhhmmmmkkkmmk..
kmhmmmmkmmmmMk..
kmmmmmkmmmmmMk..
kmmmmmmmmkmmMk..
kmmmmmmmkmMmMk..
kmmhmmmkmMMMk...
.kmmmmmmmMMMk...
.kMmmMMMMMMk....
..kMMMMMMMk.....
...kkMMMkk......
.....kkkk.......`);
  const boulder = PX.sheet([BOULDER_A, BOULDER_B, BOULDER_A, BOULDER_B]);

  /* ============================ FIRE =========================
     32x16, low ember bed, 4 frames (2 variants).               */
  const FIRE_A = f(`
................................
.......e........e...............
......ete......ете..........e...
..e...ete..e..ttett....e...ete..
..te.ttett.te.ttett...ete..ttt..
..tetttettttetttettt..ttt.tttt..
.ttetttettttettttttt.ttttttttt..
.tttttttttTtttttTttttttTttttтt..
.tTttttTttTTttttTTttttTTtttTTt..
.TTttTTTtTTTTtTTTTTtTTTTtTTTTT..
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.
rRrrRRrrrRRrRRRrrRRRrRRrrRRrrRr.
RRrRRrRRRRrrrRRrrrRRRRrRRrRRRRR.
kRkRRkRkkRRkRRkkRRkRRkkRkRRkRkk.
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
................................`.replace(/[ет]/g, c => c === 'е' ? 'e' : 't'));
  const FIRE_B = f(`
................................
..........e..........e.........
....e....ete.........ete....e...
...ete...ttt....e....ttt...ete..
...ttt..ttett..ete..ttett..ttt..
..tttt.tttettt.ttt.tttetttttt...
.tttttttttttttttttttttttttttt...
.ttTtttttTtttttTTtttttTttttTtt..
.tTTttTtTTTtttTTTTttTTTTttTTTt..
.TTTtTTTTTTTtTTTTTtTTTTTTTTTTT..
TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT.
rRrrRRrrrRRrRRRrrRRRrRRrrRRrrRr.
RRrRRrRRRRrrrRRrrrRRRRrRRrRRRRR.
kRkRRkRkkRRkRRkkRRkRRkkRkRRkRkk.
.kkkkkkkkkkkkkkkkkkkkkkkkkkkkk..
................................`);
  const fire = PX.sheet([FIRE_A, FIRE_B, FIRE_A, FIRE_B]);

  /* =========================== FLAME JET =====================
     16x64. Frames 0,1 = burning; 2,3 = OFF (blank) — the jet
     cycles by letting the animation index slide onto blank frames.  */
  function flameArt(seed) {
    const rows = [];
    for (let y = 0; y < 64; y++) {
      let row = '';
      const taper = y < 8 ? 2 + (y >> 2) : y < 48 ? 3 + ((y + seed * 3) % 3) : 5;
      const c0 = 8 - taper, c1 = 8 + taper;
      for (let x = 0; x < 16; x++) {
        if (x < c0 || x > c1) { row += '.'; continue; }
        const edge = (x === c0 || x === c1);
        const r = (x * 7 + y * 13 + seed * 29) % 10;
        if (y < 6) row += edge ? 'e' : (r < 4 ? 'e' : 't');
        else if (edge) row += r < 3 ? '.' : 't';
        else if (r < 2) row += 'e';
        else if (r < 7) row += 't';
        else row += 'T';
      }
      rows.push(row);
    }
    return f(rows.join('\n'));
  }
  const flameOff = PX.blank(16, 64);
  const flame = PX.sheet([flameArt(1), flameArt(2), flameOff, flameOff]);

  /* ========================= FIREBALL ========================
     16x40 — bouncing orb with a rising trail. 4 frames (2 arts). */
  const FB_A = f(`
................
......e.........
.....t..........
........t.......
......e..t......
....t...........
.......t........
.....t....e.....
........t.......
......t...t.....
....e...t.......
.......t..t.....
.....t..........
........t..e....
......t...t.....
....t...t.......
.......e..t.....
.....t...t......
........t.......
.....e...t......
....t..t...t....
......t..t......
....t...e..t....
.....t...t......
....kkkkkk......
...kttttttk.....
..ktttettttk....
.kttetttettтk...
.kttttetttttk...
kteтttttтettk...
ktttтeеttttttk..
kttettttettтtk..
ktttтtttttтttk..
kTtttеttтtttTk..
kTttтttttttTTk..
.kTtttтtttTTk...
.kTTttttTTTTk...
..kTTTTTTTTk....
...kTTTTTTk.....
....kkkkkk......`.replace(/[те]/g, c => c === 'т' ? 't' : 'e').replace(/е/g, 'e'));
  const FB_B = f(`
................
........t.......
......e.........
....t....t......
.......t........
.....e..........
........t..t....
......t.........
....t....e......
.......t..t.....
.....e..t.......
........t.......
......t...t.....
....t..e........
.......t...t....
.....t..t.......
....e....t......
.......t........
.....t....t.....
....t..e..t.....
......t.........
....t...t..t....
......e..t......
.....t...t......
....kkkkkk......
...kttttttk.....
..kttttetttk....
.ktttettttttk...
.ktetttettttk...
kttttttttettk...
ktteetttttttтk..
kttttttetttttk..
ktttttttttttтk..
kTttttettтtttk..
kTtttтttttтTTk..
.kTttttтttTTk...
.kTTttttTTTTk...
..kTTTTTTTTk....
...kTTTTTTk.....
....kkkkkk......`.replace(/т/g, 't'));
  const fireball = PX.sheet([FB_A, FB_B, FB_A, FB_B]);

  /* ====================== HELPER (familiar) ==================
     16x16, 4 frames (2 variants) - a cyan star-spirit.         */
  const HELP_A = f(`
.......c........
.......oc.......
......koc.......
..c..koook..a...
....koooook.....
...koooWoook....
..koooWWWoook...
.cooooWWWooooc..
..kooooWooook...
...koooooook....
....koooook.....
..a..koook..c...
......koc.......
.......oc.......
.......c........
................`);
  const HELP_B = f(`
................
.......c........
......koc.......
.....koook......
..a.koooook.a...
...koooWoook....
..cooooWooooc...
...koooooook....
....koooook.....
..a..koook..a...
......koc.......
.......c........
................
................
................`);
  const helper = PX.sheet([HELP_A, HELP_B, HELP_A, HELP_B]);

  /* ========================= STAR (pickup fx) ================
     16x16, 8 frames (4 variants repeated) - twinkling gold star. */
  const STAR_A = f(`
.......k........
......kGk.......
......kGk.......
.....kGGGk......
.kkkkGGGGGkkkk..
..kGGGGGGGGGk...
...kGGGGGGGk....
....kGGGGGk.....
....kGGGGGk.....
...kGGGkGGGk....
...kGGk.kGGk....
..kGGk...kGGk...
..kGk.....kGk...
..kk.......kk...
................
................`);
  const STAR_B = f(`
................
................
.......k........
......kGk.......
...k.kGGGk.k....
....kGGGGGk.....
.....kGGGk......
....kGGGGGk.....
...k.kGGGk.k....
......kGk.......
.......k........
................
................
................
................
................`);
  const STAR_C = f(`
.......a........
................
.......G........
................
...a..aGa..a....
................
.....G.a.G......
..G..aGGGa..G...
.....G.a.G......
................
...a..aGa..a....
................
.......G........
................
.......a........
................`);
  const star = PX.sheet([STAR_A, STAR_B, STAR_A, STAR_C, STAR_A, STAR_B, STAR_A, STAR_C]);

  /* ====================== BOTTLE (pickup fx) =================
     16x16, 8 frames (4 tumbling variants repeated).            */
  const BOT_A = f(`
......kkk.......
......ksk.......
......kok.......
.....koook......
....koooWok.....
....koooook.....
....kOooook.....
....kOOoOok.....
.....kkkkk......
................
................
................
................
................
................
................`);
  const BOT_B = f(`
................
................
....kkk.........
...kskkkk.......
...kooooook.....
..koooooWook....
..kOOooooook....
...kOOoooook....
....kkkkkkk.....
................
................
................
................
................
................
................`);
  const bottle = PX.sheet([BOT_A, BOT_B, mir(BOT_A), mir(BOT_B), BOT_A, BOT_B, mir(BOT_A), mir(BOT_B)]);

  /* ===================== GLITTER (spell aura) ================
     32x32, 4 frames (2 variants) - golden ring of sparkles.    */
  function glitterArt(big) {
    const rows = [];
    for (let y = 0; y < 32; y++) {
      let row = '';
      for (let x = 0; x < 32; x++) {
        const dx = x - 16, dy = y - 16;
        const d = Math.sqrt(dx * dx + dy * dy);
        const ring = big ? 13 : 9;
        const on = Math.abs(d - ring) < 1.2 && ((x * 5 + y * 3) % 4 === 0);
        const in2 = Math.abs(d - ring / 2) < 1 && ((x * 3 + y * 7) % 5 === 0);
        row += on ? (((x + y) & 2) ? 'a' : 'G') : in2 ? 'c' : '.';
      }
      rows.push(row);
    }
    return f(rows.join('\n'));
  }
  const glitter = PX.sheet([glitterArt(false), glitterArt(true), glitterArt(false), glitterArt(true)]);

  /* ===================== MISC POPUPS (16x16 ×2 frames each) ==
     [0]=spring puff [1]=key [2]=1up [3]=shield [4]=no-key [5]=checkpoint */
  const PUFF_A = f(`
................
.....w..w.......
...w.......w....
......www.......
....wwWWWww.....
...wWW...WWw....
..ww..... ..w...
...wWW...WWw....
....wwWWWww.....
......www.......
...w.......w....
.....w..w.......
................
................
................
................`);
  const PUFF_B = f(`
................
................
......w.w.......
....w.....w.....
......WWW.......
.....W...W......
.....W...W......
......WWW.......
....w.....w.....
......w.w.......
................
................
................
................
................
................`);
  const KEY_I = f(`
................
....kkk.........
...kGGGk........
..kGk.kGk.......
..kGk.kGk.......
...kGGGk........
....kGk.........
....kGk.........
....kGk.........
....kGkGk.......
....kGkk........
....kGkGk.......
....kGkk........
.....k..........
................
................`);
  const ONEUP = f(`
................
......kk........
.....knnk.......
....knNnnk......
....knnNnk......
...knnnNnnk.....
...knNnnnnk.....
..knnnnNnnnk....
..kkkkkkkkkk....
.kwwwwwwwwwwk...
..kkkkkkkkkk....
..1.U.P.........
................
................
................
................`);
  const SHIELD = f(`
.....kkkkk......
....koooook.....
...koocccook....
..koocWWWcook...
..kocWWWWWcok...
..kocWWoWWcok...
..kocWWWWWcok...
..koocWWWcook...
...koocccook....
....koooook.....
.....kkkkk......
................
................
................
................
................`);
  const NOKEY = f(`
................
....kkk.........
...kGGGk....rr..
..kGk.kGk..rr...
..kGk.kGk.rr....
...kGGGk.rr.....
....kGk.rr......
....kGkrr.......
....kGrr........
....krrGk.......
...rrGkk........
..rr.kGkGk......
.rr..kGkk.......
rr....k.........
................
................`);
  const CHECK_I = f(`
.......kk.......
......kook......
.....koWWok.....
.....koWWok.....
......kook......
.......kk.......
......kook......
.....kooook.....
....koooooook...
.....kooook.....
......kook......
.......kk.......
.......kk.......
......kook......
.....kkkkkk.....
................`);
  function twin(fr) { return [fr, fr]; }
  const misc = [PX.sheet([PUFF_A, PUFF_B]), PX.sheet(twin(KEY_I)), PX.sheet(twin(ONEUP)),
                PX.sheet(twin(SHIELD)), PX.sheet(twin(NOKEY)), PX.sheet(twin(CHECK_I))];

  /* ========================= PLATFORMS ======================= */
  const HPLAT = f(`
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
ksssssskssssssssksssssskssssssik
kssWsssksssWssssksssWsskssWsssik
kSssssSkSsssssSskSssssSkSssssSik
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
..kSk....kSk........kSk...kSk...
...kSk..kSk..........kSk.kSk....
....kkkkk..............kkkk.....
................................`);
  const VPLAT = f(`
.....kGk......kGk...............
.....kGk......kGk...............
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
kzzzzzzzzhzzzzzzzzzzhzzzzzzzzzzk
kzhzzzzzzzzzzzhzzzzzzzzzhzzzzzzk
kzzzzhzzzzzzzzzzzzhzzzzzzzzzzhzk
kZzzzzzzZzzzzzzZzzzzzzZzzzzzzZzk
kZZzzzZZZZzzzZZZZzzZZZZzzzZZZZzk
kkZZZZkkkkZZZZkkkkZZZkkkkZZZkkk.
.kkkkk...kkkkk....kkkk...kkkk...
................................
................................`);
  const FPLAT = f(`
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
kssssksskssssssskksssskssssssssk
ksWssksskssWssssкksssskssWsssssk
kSsssksskSssssssкkssssкSssssssSk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
...kmk....kmk......kmk...kmk....
...kMk.....kMk....kMk....kMk....
....kMk....kMk....kMk...kMk.....
....kkk....kkk....kkk...kkk.....
......k.....k......k.....k......
.......................k........
.....k.........k................
................................
................................
................................
................................`.replace(/к/g, 'k'));
  const hplat = PX.sheet([HPLAT]);
  const vplat = PX.sheet([VPLAT]);
  const fplat = PX.sheet([FPLAT]);

  /* =========================== BOSSES ========================
     Drawn 32x32 / 32x16, scaled ×2 for that big-chunky look.
     boss:  [0]=head 64x64  [1]=coil segment 64x64
     boss2: [0]=head 64x32  [1]=fin segment 64x32               */
  const BOSS_HEAD = f(`
..........kk....kk..............
.........kGGk..kGGk.............
........kGGGGkkGGGGk............
........kgGGgkkgGGgk............
.......kvgGgvvvgGGgk............
......kvvgggvvvgggvvk...........
.....kvvvvvvvvvvvvvvk...........
....kvvVVvvvvvvvVVvvvk..........
...kvvVVVVvvvvvVVVVvvvk.........
..kvvvVVVVvvvvvVVVVvvvvk........
..kvvvvVVvvvvvvvVVvvvvvk........
.kvvvvvvvvvvvvvvvvvvvvvvk.......
.kvvkkkvvvvvvvvvvvkkkvvvk.......
kvvkGGGkvvvvvvvvvkGGGkvvvk......
kvvkGoGkvvvvvvvvvkGoGkvvvk......
kvvkGGGkvvvvvvvvvkGGGkvvvk......
kvvvkkkvvvvvvvvvvvkkkvvvvk......
kvvvvvvvvvvvvvvvvvvvvvvvvk......
kvVvvvvvvvvvvvvvvvvvvvvVvk......
kvVVvvvvvvvvvvvvvvvvvvVVvk......
.kvVVvvvvvvvvvvvvvvvvVVvk.......
.kkvvvvvkkkkkkkkkvvvvvvkk.......
..kkvvkkwwkwwkwwkkkvvkk.........
...kkkkwwkwwkwwkwwkkkk..........
....kVkkwkkwkkwkkwkkVk..........
....kVVkkkkkkkkkkkkVVk..........
.....kVVVVVVVVVVVVVVk...........
......kkVVVVVVVVVVkk............
........kkkkkkkkkk..............
................................
................................
................................`);
  const BOSS_SEG = f(`
................................
................................
................................
..........kkkkkkkk..............
........kkvvvvvvvvkk............
......kkvvvvVVvvvvvvkk..........
.....kvvvvVVVVVVvvvvvvk.........
....kvvvvVVvvvvVVvvvvvvk........
...kvvvvVVvvvvvvVVvvvvvvk.......
...kvvvVVvvvvvvvvVVvvvvvk.......
..kvvvvVvvvvvvvvvvVvvvvvvk......
..kvvvvvvvvkkkkvvvvvvvvvvk......
..kvvvvvvvkGGGGkvvvvvvvvvk......
.kvvvvvvvkGGggGGkvvvvvvvvvk.....
.kvvvvvvvkGgGGgGkvvvvvvvvvk.....
.kvvvvvvvkGGggGGkvvvvvvvvvk.....
.kvvvvvvvvkGGGGkvvvvvvvvvvk.....
..kvvvvvvvvkkkkvvvvvvvvvvk......
..kvvvvvVvvvvvvvvvVvvvvvvk......
..kvvvvVVvvvvvvvvVVvvvvvk.......
...kvvVVvvvvvvvvVVvvvvvvk.......
...kvvVvvvvvvvvvvVVvvvvk........
....kvvvVVvvvvVVvvvvvvk.........
.....kvvvvVVVVVVvvvvvk..........
......kkvvvvVVvvvvvkk...........
........kkvvvvvvvkk.............
..........kkkkkkk...............
................................
................................
................................
................................
................................`);
  const boss = PX.sheet([scale(BOSS_HEAD, 2), scale(BOSS_SEG, 2)]);

  const BOSS2_HEAD = f(`
.......kkkk.....................
....kkkrrrrkk...................
...krrrrRRrrrk......kkk.........
..krrkkrrrrRrrk....krrrk........
.krrkGGkrrrrRrrkkkkrrRrk........
.krkGoGkrrrrrrrrrrrrRrrk........
.krrkGGkrrrrrrrrrrrRrrk.........
..krrkkrrrrrrrrrrrrrrk..........
..krrrrrrrkkkkrrrrrrk...........
...krrrrkkwwwwkkrrrrk...........
....kkrrkwkwkwkwkrrk............
.....kkwwkwwkwwkwwk.............
......kkkkkkkkkkkk..............
........kRRRRRRk................
.........kkRRkk.................
..........kkkk..................`);
  const BOSS2_SEG = f(`
..........kkkk..................
........kkrrrrkk......k.........
......kkrrrRRrrrkk...kek........
.....krrrRRrrRRrrrk..kтek.......
....krrrRRrrrrRRrrrkkkтek.......
....krrRRrrkkrrRRrrrrkтk........
....krrRrrkGGkrrRrrrrkek........
....krrRrrkGGkrrRrrrrkтk........
....krrRRrrkkrrRRrrrкеk.........
.....krrrRRrrRRrrrk.kтk.........
......kkrrrRRrrrkk...k..........
........kkrrrrkk................
..........kkkk..................
................................
................................
................................`.replace(/[те]/g, c => c === 'т' ? 't' : 'e').replace(/к/g, 'k').replace(/е/g, 'e'));
  const boss2 = PX.sheet([scale(BOSS2_HEAD, 2), scale(BOSS2_SEG, 2)]);

  /* ===== sprite type table ===== */
  return {
    list: [wiz, guard, knight, dragon, arrow, star, vplat, hplat, bottle, fire,
           null /*misc handled separately*/, sentry, glitter, fireball, flame, boulder,
           helper, fplat, fish, archer, boss, ghost, boss2],
    wiz, guard, knight, dragon, arrow, star, vplat, hplat, bottle, fire,
    sentry, glitter, fireball, flame, boulder, helper, fplat, fish, archer,
    boss, ghost, boss2, misc,
  };
})();
