// tiles.js — terrain, decor, items, HUD pieces, and per-theme parallax skies.
// Terrain, decor, items, HUD pieces, and per-theme parallax skies.
'use strict';

const TILES = (() => {
  const PAL = PX.palette({
    k: '#1a1129', K: '#0d0817',
    g: '#56b14a', G: '#3c8a36', l: '#7dd45e',
    d: '#7a4f30', D: '#5d3a22', e: '#432914',
    s: '#8d97b8', S: '#6c7694', t: '#4e5570', h: '#aab4d0',
    m: '#5a8a50',
    b: '#9aa3bd', B: '#787f9a', c: '#565d78',
    z: '#6e5a86', Z: '#4a3a60', x: '#8d76aa',
    o: '#7df0ff', O: '#2ab8d8',
    w: '#a06a38', W: '#c08a50', v: '#7a4a22',
    y: '#ffd75e', Y: '#c79a2a', a: '#fff1a8',
    r: '#e04f2a', R: '#9c2e1a',
    f: '#f4f6ff', F: '#c9d2ec',
    p: '#bd5cd6', P: '#8a3aa0',
    n: '#2e49b8', N: '#1f2f7e',
    q: '#ff9a3c',
    u: '#3a2a52', U: '#2a1d3e', i: '#514070',
    j: '#1d1532', J: '#251a40',
  });
  const f = (art) => PX.frame(art, PAL);
  const mir = PX.mirror;

  /* ----------------------------- terrain ----------------------------- */
  const turfCap = f(`
glgglggllgglgglg
gGgggGggggGgggGg
GdGGdDGGdGGDdGGD
ddDdddDdddDDdddd
dDdddDdddDdddDdd
ddddDdddDdddddDd
dDdDdddddddDdddd
ddddddDddDdddddD
dDddDdddddddDddd
dddDdddDddDddddd
DdddddddDdddDddD
ddDddDdddddddddd
dDdddddDddDdDddd
dddDdddddDdddddd
DddddDdddddDddDd
dDdddddDdddddddd`);
  const turfFill = f(`
ddDdddDdddDDdddd
dDdddDdddDdddDdd
ddddDdddDdddddDd
dDdDdddddddDdddd
ddddddDddDdddddD
dDddDdddddddDddd
dddDdddDddDddeed
DdddddddDdddDeeD
ddDddDdddddddddd
dDdddddDddDdDddd
ddeeDdddddDddddd
DdeedDdddddDddDd
dDdddddDdddddddd
ddDdddDdddDDddee
dDdddDdddDdddDee
ddddDdddDdddddDd`);
  const stone = f(`
kkkkkkkkkkkkkkkk
khsssssshssssssk
kssSssssssssSssk
ksssssSssssssssk
kSssssssssSsssSk
kssSsssSssssssssk
kkkkkkkkkkkkkkkk
ksssShsssssShssk
kshssssssSssssskk
ksssssSsssssSssk
kSsssssssssssstk
kkkkkkkkkkkkkkkk
khssssShsssssssk
kssSsssssssSsssk
ksssssssSsssssttk
kkkkkkkkkkkkkkkk`);
  const stoneMoss = f(`
kkkkkkkkkkkkkkkk
kmsssssshssmmssk
kmmSsssssssssmsk
ksssssSssssssssk
kSssssssssSsssSk
kssSsssSsssssssk
kkkkkkkkkkkkkkkk
ksssShsssssShssk
kshssssssSsssssk
kmssssSsssssSssk
kmmsssssssssssttk
kkkkkkkkkkkkkkkk
khssssShssssmmsk
kssSsssssssSmssk
ksssssssSsssssttk
kkkkkkkkkkkkkkkk`);
  const caveRock = f(`
zzZzzzxzzzZzzzxz
zZzzzzzzZzzzZzzz
zzzxzzZzzzzzzzZz
Zzzzzzzzzxzzzzzz
zzZzzxzzzzzZzzzz
zzzzzzzZzzzzzxzz
zxzzZzzzzZzzzzzZ
zzzzzzxzzzzzzZzz
zZzzzzzzzZzxzzzz
zzzxzZzzzzzzzzZz
zzzzzzzzxzzZzzzz
ZzzZzzzzzzzzzzxz
zzzzzxzzZzzzZzzz
zxzzzzzzzzxzzzzZ
zzzZzzzxzzzzzZzz
zzzzzzzzzZzzzzzz`);
  const caveCrystal = f(`
zzZzzzxzzzZzzzxz
zZzzzzzzZzzzZzzz
zzzxzzZzzzokzzZz
Zzzzzzzzzkookzzz
zzZzzxzzzkoOkzzz
zzzzzzzZzkOkzxzz
zxzzZzzzzzkzzzzZ
zzzzzzxzzzzzzZzz
zZzokzzzzZzxzzzz
zzkookZzzzzzzzZz
zzkoOkzzxzzZzzzz
ZzzkOkzzzzzzzzxz
zzzzkxzzZzzzZzzz
zxzzzzzzzzxzzzzZ
zzzZzzzxzzzzzZzz
zzzzzzzzzZzzzzzz`);
  const brick = f(`
bbbkbbbbbbbkbbbb
bBbkbBbbbBbkbbBb
bbbkbbbbbbbkbBbb
kkkkkkkkkkkkkkkk
bbbbbkbbbbbbbkbb
bBbbbkbbBbbbbkbB
bbbbbkbbbbBbbkbb
kkkkkkkkkkkkkkkk
bbkbbbbbbkbbbbbb
bbkbbBbbbkbbBbbb
bBkbbbbbbkbbbbBb
kkkkkkkkkkkkkkkk
bbbbbbkbbbbbbbkb
bbBbbbkbbbBbbbkb
bbbbbbkbbbbbbbkb
kkkkkkkkkkkkkkkk`);
  const brickCrack = f(`
bbbkbbbbbbbkbbbb
bBbkbBkbbBbkbbBb
bbbkbbkbbbbkbBbb
kkkkkkkkkkkkkkkk
bbbbbkbbbbkbbkbb
bBbbbkbbBbbkbkbB
bbbbbkbbbbBbkkbb
kkkkkkkkkkkkkkkk
bbkbbbbbbkkbbbbb
bbkbbBbbkbbkBbbb
bBkbbbbkbbbbkbBb
kkkkkkkkkkkkkkkk
bbbbbbkbbbbbbbkb
bbBbbbkbbbBbbbkb
bbbbbbkbbbbbbbkb
kkkkkkkkkkkkkkkk`);
  const wood = f(`
kkkkkkkkkkkkkkkk
kWwwwkwwwwkwwwwk
kwwWwkwWwwkwwWwk
kvwwwkwwwvkwvwwk
kkkkkkkkkkkkkkkk
....kvk..kvk....
....kvk..kvk....
.....kvk.kvk....
.....kvkkvk.....
......kvkv......
......kvkv......
.......kk.......
................
................
................
................`);
  const runeOn = f(`
kkkkkkkkkkkkkkkk
kyyyyyyyyyyyyyyk
kyaYYYYYYYYYYayk
kyYyyyyyyyyyyYyk
kyYyykkkkkkyyYyk
kyYyyk..aykyyYyk
kyYyak.akkkyyYyk
kyYyyk.kaykyyYyk
kyYyykak.ykyyYyk
kyYyakk..kkyyYyk
kyYyykkkkkkyyYyk
kyYyyyyyyyyyyYyk
kyaYYYYYYYYYYayk
kyyyyyyyyyyyyyyk
kkkkkkkkkkkkkkkk
................`);
  const runeOff = f(`
uuuu.uu.uu.uuuu.
u..............u
u..............u
u...........u..u
....uuuuuu......
u...u....u.....u
u...u....u......
....u....u.....u
u...u....u......
u...uuuuuu.....u
................
u..u...........u
u..............u
.uuu.uu.uu.uuuu.
................
................`);
  const interiorBrick = f(`
jjjJjjjjjjjJjjjj
jJjJjJjjjJjJjjJj
jjjJjjjjjjjJjJjj
JJJJJJJJJJJJJJJJ
jjjjjJjjjjjjjJjj
jJjjjJjjJjjjjJjJ
jjjjjJjjjjJjjJjj
JJJJJJJJJJJJJJJJ
jjJjjjjjjJjjjjjj
jjJjjJjjjJjjJjjj
jJJjjjjjjJjjjjJj
JJJJJJJJJJJJJJJJ
jjjjjjJjjjjjjjJj
jjJjjjJjjjJjjjJj
jjjjjjJjjjjjjjJj
JJJJJJJJJJJJJJJJ`);
  const windowT = f(`
jjjjjkkkkkkjjjjj
jjjjkknnnkkkjjjj
jjjkknnNnnnkkjjj
jjkknnnnnnnnkkjj
jjknnnNnnnNnnkjj
jjknnnnnnnnnnkjj
jjknNnnnnnnNnkjj
jjknnnnnNnnnnkjj
jjknnnnnnnnnnkjj
jjknnNnnnnNnnkjj
jjknnnnnnnnnnkjj
jjkknnnnnnnnkkjj
jjjkknnnnnnkkjjj
jjjjkknnnnkkjjjj
jjjjjkkkkkkjjjjj
jjjjjjjjjjjjjjjj`);
  const banner = f(`
....kkkkkkkk....
....krrrrrrk....
....krRrrRrk....
....krrrrrrk....
....krryyrrk....
....kryaayrk....
....kryaayrk....
....krryyrrk....
....krrrrrrk....
....krRrrRrk....
....krrrrrrk....
....krrrrrk.....
....krrrrk......
....krrrk.......
....krrk........
....kkk.........`);

  /* ------------------------ interactive fore tiles ------------------------ */
  const spring = f(`
................
................
................
................
................
....kkkkkkkk....
...krrrrrrrrk...
...kRrrrrrrRk...
....kkkkkkkk....
.....ykykyk.....
....kykykyk.....
.....ykykyk.....
....kykykyk.....
....kkkkkkkk....
...kssssssssk...
...kkkkkkkkkk...`);
  const leverL = f(`
................
................
................
..kk............
.kook...........
.kook...........
..kksk..........
....ksk.........
.....ksk........
......ksk.......
......kssk......
....kkkkkkkk....
...kssssssssk...
...kskkkkkksk...
...kkkkkkkkkk...
................`);
  const leverR = mir(leverL);

  /* ------------------------------- decor ------------------------------- */
  const torchA = f(`
................
......aa........
.....qaaq.......
.....qaaq.......
....qqaaqq......
....qraarq......
....qrqqrq......
.....krrk.......
......kk........
.....kWwk.......
.....kwwk.......
......kwk.......
....kkwwkk......
.....kkkk.......
................
................`);
  const torchB = f(`
................
................
......aa........
....qaaaq.......
....qaaaqq......
....qqaaqq......
....qraarq......
.....krrk.......
......kk........
.....kWwk.......
.....kwwk.......
......kwk.......
....kkwwkk......
.....kkkk.......
................
................`);
  const tuft = f(`
................
................
................
................
................
................
................
................
................
................
.....l..l.......
..l..l.g..l.....
..g.l.gg.g......
...g.gg.gg..l...
..gg.g.g.g.g....
................`);
  const flowerA = f(`
................
................
................
................
................
................
......pp........
.....paap.......
......pp........
.......G........
.......G........
....G..G........
.....G.G..G.....
......GG.G......
......GG.G......
................`);
  const flowerB = f(`
................
................
................
................
................
................
...yy...........
..yaay.....pp...
...yy.....paap..
....G......pp...
....G.......G...
....G..G....G...
.....G.G...G....
......GG..G.....
......GG.G......
................`);
  const mushroom = f(`
................
................
................
................
................
................
................
....kkkkkk......
...krrrrrrk.....
..krrfrrfrrk....
..krrrrrrrrk....
...kkkffkkk.....
.....kffk.......
.....kffk.......
....kkffkk......
................`);
  const bush = f(`
................
................
................
................
.....kkkk.......
...kkggggkk.....
..kgglgglggk....
.kggglggglggk...
.kglgggggglgk...
kgggglgglggggk..
kglgggggggglgk..
kgggGGgGGggggk..
.kGGgGGGgGGGk...
..kkGGgGGGkk....
....kkkkkk......
................`);
  const fence = f(`
................
................
................
................
................
.kwk........kwk.
.kwkwwwwwwwwkwk.
.kwk........kwk.
.kwk........kwk.
.kwkwwwwwwwwkwk.
.kwk........kwk.
.kwk........kwk.
................
................
................
................`);
  const stalag = f(`
................
................
................
................
................
................
.......zk.......
......kzZk......
......kzZk......
.....kzzZZk.....
.....kzzZZk.....
....kzzzZZk.....
....kzzzZZZk....
...kzzzzZZZk....
..kzzzzzZZZZk...
................`);
  const skull = f(`
................
................
................
................
................
................
................
................
................
.....kkkk.......
....kffffk......
....kfkfkfk.....
....kffffk......
.....kfkfk......
.....kkkkk......
................`);

  /* ------------------------------ items ------------------------------ */
  const potionItem = f(`
......kkk.......
......kfk.......
......kok.......
.....koook......
....koooook.....
...koooWoook....
...kooWooook....
...kOoooooOk....
...kOOooooOk....
....kOOooOk.....
.....kkkkk......
................
................
................
................
................`);
  const items = {
    1: SPRITES.star.frames[0],
    2: potionItem,
    3: SPRITES.misc[2].frames[0],
    4: SPRITES.misc[1].frames[0],
    6: SPRITES.misc[3].frames[0],
  };

  /* ------------------------------ doors ------------------------------ */
  const doorClosed = f(`
.....kkkkkkkkkkkkkkkkkkkkk......
....kssWWwwwwwwwwwwwwWWssk.....
...kssWwwwwwkkkkwwwwwwWssk.....
..kssWwwwkkkwwwwkkkwwwwWssk....
..ksWwwkkwwwwwwwwwwkkwwWWsk....
..ksWwkwwwwwwkkwwwwwwkwWWsk....
..ksWwkwwwwwkwwkwwwwwkwWWsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwkkwwwwwwwwwwkkwkwwsk....
..kswkwwwwwwwkkwwwwwwwkwwsk....
..kswkwwwwwwkwwkwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwkkwwwwwwwwwkkwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwywwwkwwsk....
..kswkwwwwwwwwwwwkykwwkwwsk....
..kswkwwwwwwwwwwwkykwwkwwsk....
..kswkwwwwwwwwwwwwywwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswwkkkkkkkkkkkkkkkkwwwsk....
..ksswwwwwwwwwwwwwwwwwwwssk....
..kkkkkkkkkkkkkkkkkkkkkkkkk....
................................`);
  const doorLocked = f(`
.....kkkkkkkkkkkkkkkkkkkkk......
....kssWWwwwwwwwwwwwwWWssk.....
...kssWwwwwwkkkkwwwwwwWssk.....
..kssWwwwkkkwwwwkkkwwwwWssk....
..ksWwwkkwwwwwwwwwwkkwwWWsk....
..ksWwkwwwwwwkkwwwwwwkwWWsk....
..ksWwkwwwwwkwwkwwwwwkwWWsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwkkwwwwwwwwwwkkwkwwsk....
..kswkwwwwwwwkkwwwwwwwkwwsk....
..kswkwwwwwwkwwkwwwwwwkwwsk....
..kswkwwwwkkkkkkkkwwwwkwwsk....
..kswkwwwkyyyyyyyykwwwkwwsk....
..kswkwwwkyykkkkyykwwwkwwsk....
..kswkwwwkykkyykkykwwwkwwsk....
..kswkwwwkyykkkkyykwwwkwwsk....
..kswkwwwkyyykkyyykwwwkwwsk....
..kswkwwwkyyykkyyykwwwkwwsk....
..kswkwwwkyyyyyyyykwwwkwwsk....
..kswkwwwwkkkkkkkkwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswkwwwwwwwwwwwwwwwwkwwsk....
..kswwkkkkkkkkkkkkkkkkwwwsk....
..ksswwwwwwwwwwwwwwwwwwwssk....
..kkkkkkkkkkkkkkkkkkkkkkkkk....
................................`);
  const doorOpen = f(`
.....kkkkkkkkkkkkkkkkkkkkk......
....kssWWKKKKKKKKKKKKWWssk.....
...kssWKKKKKKKKKKKKKKKWssk.....
..kssWKKKKKKKKKKKKKKKKKWssk....
..ksWKKKKKKKKKKKKKKKKKKWWsk....
..ksWKKKKKKKKKKKKKKKKKKWWsk....
..ksWKKKKKKKKKKKKKKKKKKWWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..ksKKKKKKKKKKKKKKKKKKKKWsk....
..kssKKKKKKKKKKKKKKKKKKssk.....
..kkkkkkkkkkkkkkkkkkkkkkkkk....
................................`);

  /* checkpoint waystone, 16x32, dim / lit */
  const wayDim = f(`
................
......kkk.......
.....kzzzk......
....kzzzzzk.....
....kzizizk.....
....kzzizzk.....
....kzizizk.....
....kzzzzzk.....
....kzizzik.....
....kzzizzk.....
.....kzzzk......
.....kzzzk......
.....kzzzk......
....kzzzzzk.....
....kzzzzzk.....
...kzzzzzzzk....
...kzzzzzzzk....
..kzzzzzzzzzk...
..kkkkkkkkkkk...
................
................
................
................
................
................
................
................
................
................
................
................
................`);
  const wayLit = f(`
.......a........
......kok.......
.....koook......
....koooook.....
....koaoaok.....
....kooaook.....
....koaoaok.....
....kzooozk.....
....kzaozak.....
....kzzazzk.....
.....kzozk......
.....kzozk......
.....kzozk......
....kzzozzk.....
....kzzozzk.....
...kzzzozzzk....
...kzzzzzzzk....
..kzzzzzzzzzk...
..kkkkkkkkkkk...
................
................
................
................
................
................
................
................
................
................
................
................
................
................`);

  /* exit arch 48x48, built in code: stone arch + EXIT glow */
  const exitArch = (() => {
    const cv = document.createElement('canvas');
    cv.width = 48; cv.height = 48;
    const c = cv.getContext('2d');
    c.fillStyle = '#1a1129';
    c.fillRect(2, 10, 44, 38);
    c.fillStyle = '#6c7694';
    c.fillRect(4, 12, 40, 36);
    c.fillStyle = '#8d97b8';
    c.fillRect(6, 12, 36, 34);
    // dark portal opening
    c.fillStyle = '#0d0817';
    c.beginPath();
    c.moveTo(12, 48); c.lineTo(12, 24);
    c.quadraticCurveTo(24, 10, 36, 24); c.lineTo(36, 48); c.closePath();
    c.fill();
    // inner glow
    c.fillStyle = '#2ab8d822';
    c.fillRect(14, 26, 20, 22);
    // keystone + EXIT sign
    c.fillStyle = '#1a1129'; c.fillRect(13, 2, 22, 10);
    c.fillStyle = '#3c8a36'; c.fillRect(14, 3, 20, 8);
    PX.drawText(c, 'EXIT', 15, 4, '#aef4ff');
    return { canvas: cv, w: 48, h: 48, mask: new Uint8Array(48 * 48) };
  })();

  /* ------------------------- HUD: flask + spell icons ------------------------- */
  function spellIcon(art) { return f(art); }
  const ICON_HIJUMP = spellIcon(`
....kkkk....
...kyyyyk...
..kya..ayk..
..ky.kk.yk..
..ky.kk.yk..
..kykkkkyk..
..kyk..kyk..
.kyk....kyk.
.kyakkkkayk.
..kyyyyyyk..
...kkkkkk...
............`);
  const ICON_INVIS = spellIcon(`
............
..kkkkkkkk..
.koooooook..
koofkkkfook.
kofkokokfok.
koofkkkfook.
.koooooook..
..kkkkkkkk..
.....k......
....kok.....
.....k......
............`);
  const ICON_DJUMP = spellIcon(`
.....kk.....
....kook....
...kooook...
..koo..ook..
.....kk.....
....kook....
...kooook...
..koo..ook..
.....kk.....
....kook....
...kkkkkk...
............`);
  const ICON_FLAME = spellIcon(`
.....k......
....kqk.....
....kqak....
...kqaqk....
...kqaaqk...
..kqaaaqk...
..kqarraqk..
.kqaraaraqk.
.kqaraaraqk.
..kqarraqk..
...kqqqqk...
............`);
  const ICON_WISP = spellIcon(`
.....k......
....kok.....
...koook....
.kkoooookk..
koooofooook.
.kkoooookk..
...koook....
....kok.....
.....k......
..a.....a...
............
............`);
  const ICON_RESTORE = spellIcon(`
....kkkk....
...kyyyyk...
..ky.kk.yk..
.kyk.kk.kyk.
.ky.kkkk.yk.
.ky.kkkk.yk.
.kyk.kk.kyk.
..ky.kk.yk..
...kyyyyk...
....kkkk....
............
............`);
  const spellIcons = [ICON_HIJUMP, ICON_INVIS, ICON_DJUMP, ICON_FLAME, ICON_WISP, ICON_RESTORE];

  const lifeIcon = f(`
....kk......
...knnk.....
..knNnnk....
..knnNnk....
.knnnNnnk...
.knNnnnnk...
knnnnNnnnk..
kkkkkkkkkk..
.kffkkffk...
..kkkkkk....`);

  // flask: drawn programmatically with a fill fraction
  function drawFlask(ctx, x, y, frac) {
    ctx.fillStyle = '#1a1129';
    ctx.fillRect(x + 6, y, 8, 3);
    ctx.fillRect(x + 7, y + 2, 6, 4);
    ctx.beginPath();
    ctx.arc(x + 10, y + 16, 9, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#2a1d3e';
    ctx.beginPath();
    ctx.arc(x + 10, y + 16, 7, 0, Math.PI * 2);
    ctx.fill();
    if (frac > 0) {
      const h = Math.max(1, Math.round(14 * frac));
      ctx.save();
      ctx.beginPath();
      ctx.arc(x + 10, y + 16, 7, 0, Math.PI * 2);
      ctx.clip();
      ctx.fillStyle = '#bd5cd6';
      ctx.fillRect(x + 1, y + 23 - h, 18, h);
      ctx.fillStyle = '#dba2e8';
      ctx.fillRect(x + 1, y + 23 - h, 18, 1);
      ctx.restore();
    }
    ctx.fillStyle = '#aab4d0';
    ctx.fillRect(x + 7, y + 1, 6, 2);
  }

  /* ------------------------------ themes ------------------------------ */
  function silhouetteLayer(w, h, color, drawFn) {
    const cv = document.createElement('canvas');
    cv.width = w; cv.height = h;
    const c = cv.getContext('2d');
    c.fillStyle = color;
    drawFn(c, w, h);
    return cv;
  }

  function hills(c, w, h) {
    c.beginPath(); c.moveTo(0, h);
    for (let x = 0; x <= w; x += 8) {
      const y = h - 26 - 18 * Math.sin(x * 0.013) - 9 * Math.sin(x * 0.031 + 2);
      c.lineTo(x, y);
    }
    c.lineTo(w, h); c.closePath(); c.fill();
  }
  function pines(c, w, h) {
    for (let x = 6; x < w; x += 22) {
      const ph = 34 + 18 * Math.abs(Math.sin(x * 1.7));
      c.beginPath();
      c.moveTo(x, h); c.lineTo(x, h - ph);
      c.lineTo(x - 9, h); c.closePath(); c.fill();
      c.beginPath();
      c.moveTo(x, h); c.lineTo(x, h - ph);
      c.lineTo(x + 9, h); c.closePath(); c.fill();
    }
  }
  function towers(c, w, h) {
    for (let x = 10; x < w; x += 74) {
      const tw = 26 + (x * 13 % 18), th = 50 + (x * 7 % 38);
      c.fillRect(x, h - th, tw, th);
      for (let mx = x - 3; mx < x + tw + 3; mx += 7) c.fillRect(mx, h - th - 6, 4, 7);
      c.fillRect(x + tw / 2 - 2, h - th - 16, 5, 12);
    }
  }
  function spikesDown(c, w, h) {
    for (let x = 0; x < w; x += 14) {
      const sh = 20 + 16 * Math.abs(Math.sin(x * 0.9));
      c.beginPath();
      c.moveTo(x, 0); c.lineTo(x + 7, sh); c.lineTo(x + 14, 0);
      c.closePath(); c.fill();
    }
  }

  const THEMES = {
    meadow: {
      sky: ['#3a7bd5', '#4a8be0', '#5e9ce8', '#74aff0', '#8ec2f6', '#a8d4fa'],
      sun: { x: 380, y: 42, r: 16, color: '#fff1a8', glow: '#fff1a833' },
      far: silhouetteLayer(480, 256, '#5e87c8', hills),
      near: silhouetteLayer(480, 256, '#4a6fb0', (c, w, h) => { hills(c, w, h); pines(c, w, h); }),
      ground: { cap: turfCap, fill: turfFill }, solid: { cap: stone, fill: stone, alt: stoneMoss },
      flora: [tuft, tuft, flowerA, flowerB, bush, mushroom, fence],
      stars: false,
    },
    forest: {
      sky: ['#2a2a5e', '#3a3470', '#4c3e82', '#64488e', '#84549a', '#a4609e'],
      sun: { x: 90, y: 60, r: 14, color: '#ffd0a0', glow: '#ff9a3c33' },
      far: silhouetteLayer(480, 256, '#3a3068', hills),
      near: silhouetteLayer(480, 256, '#2a2450', (c, w, h) => pines(c, w, h)),
      ground: { cap: turfCap, fill: turfFill }, solid: { cap: stoneMoss, fill: stone, alt: stoneMoss },
      flora: [tuft, mushroom, mushroom, bush, flowerB, tuft],
      stars: true,
    },
    cave: {
      sky: ['#171026', '#1b1230', '#1f163a', '#241a42', '#241a42', '#1f163a'],
      sun: null,
      far: silhouetteLayer(480, 256, '#241a42', (c, w, h) => { spikesDown(c, w, h); hills(c, w, h); }),
      near: silhouetteLayer(480, 256, '#170f28', spikesDown),
      ground: { cap: caveRock, fill: caveRock, alt: caveCrystal }, solid: { cap: caveRock, fill: caveRock, alt: caveCrystal },
      flora: [stalag, skull, mushroom, stalag],
      stars: false,
    },
    castle: {
      sky: ['#e8865e', '#e07060', '#c45e74', '#9c4e80', '#744284', '#543a7c'],
      sun: { x: 110, y: 78, r: 18, color: '#ffe8b0', glow: '#ffb05033' },
      far: silhouetteLayer(480, 256, '#8a4a78', towers),
      near: silhouetteLayer(480, 256, '#5e3768', towers),
      ground: { cap: brick, fill: brick, alt: brickCrack }, solid: { cap: brick, fill: brick, alt: brickCrack },
      flora: [banner, torchA],
      stars: false,
    },
    dungeon: {
      sky: null, back: interiorBrick,
      sun: null,
      far: null, near: null,
      ground: { cap: brick, fill: brick, alt: brickCrack }, solid: { cap: brick, fill: brick, alt: brickCrack },
      flora: [banner, windowT, torchA],
      stars: false,
    },
    court: {
      sky: ['#0d0f2e', '#12143a', '#181a48', '#202158', '#2a2a66', '#343274'],
      sun: { x: 360, y: 40, r: 14, color: '#f4f6ff', glow: '#c9d2ec33' },
      far: silhouetteLayer(480, 256, '#1d1d52', towers),
      near: silhouetteLayer(480, 256, '#121240', towers),
      ground: { cap: brick, fill: brick, alt: brickCrack }, solid: { cap: stone, fill: stone, alt: stoneMoss },
      flora: [banner, torchA],
      stars: true,
    },
  };

  // deterministic star field
  const STARS = [];
  for (let i = 0; i < 70; i++) {
    STARS.push({ x: (i * 97 + 31) % 480, y: (i * 53 + 11) % 130, s: i % 3 === 0 ? 2 : 1 });
  }

  function drawSky(ctx, theme, lx, t) {
    const th = THEMES[theme];
    if (!th.sky) { // interior: tiled brick
      for (let y = 0; y < 16; y++)
        for (let x = 0; x < 31; x++)
          ctx.drawImage(th.back.canvas, x * 16 - (lx * 0.3 % 16), y * 16);
      ctx.fillStyle = '#00000055';
      ctx.fillRect(0, 0, 480, 256);
      return;
    }
    const bands = th.sky;
    const bh = Math.ceil(256 / bands.length);
    bands.forEach((col, i) => {
      ctx.fillStyle = col;
      ctx.fillRect(0, i * bh, 480, bh);
    });
    if (th.stars) {
      for (const s of STARS) {
        const tw = ((t >> 3) + s.x) % 7 === 0 ? 0.4 : 1;
        ctx.globalAlpha = tw;
        ctx.fillStyle = '#f4f6ff';
        ctx.fillRect((s.x - lx * 0.06) % 480 + (((s.x - lx * 0.06) % 480) < 0 ? 480 : 0), s.y, s.s, s.s);
      }
      ctx.globalAlpha = 1;
    }
    if (th.sun) {
      const sx = th.sun.x - lx * 0.02;
      ctx.fillStyle = th.sun.glow;
      ctx.beginPath(); ctx.arc(sx, th.sun.y, th.sun.r * 2.2, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = th.sun.color;
      ctx.beginPath(); ctx.arc(sx, th.sun.y, th.sun.r, 0, Math.PI * 2); ctx.fill();
    }
    if (th.far) {
      const o = (lx * 0.15) % 480;
      ctx.drawImage(th.far, -o, 0); ctx.drawImage(th.far, 480 - o, 0);
    }
    if (th.near) {
      const o = (lx * 0.3) % 480;
      ctx.drawImage(th.near, -o, 0); ctx.drawImage(th.near, 480 - o, 0);
    }
  }

  return {
    THEMES, drawSky, items, potionItem,
    wood, runeOn, runeOff, spring, leverL, leverR,
    doorClosed, doorLocked, doorOpen, exitArch, wayDim, wayLit,
    torchA, torchB, windowT, banner,
    spellIcons, lifeIcon, drawFlask,
    keyIcon: SPRITES.misc[1].frames[0],
  };
})();
